services:
  exchange:
    build:
      context: ..
      dockerfile: docker/Dockerfile
    volumes:
      - ../config:/config
    restart: unless-stopped
    networks:
      - network

networks:
  network:
    external: true
    name: network
